"""Init DB: core, auth, clinica, sys

Revision ID: 291a9f0008ca
Revises: 
Create Date: 2026-07-26 23:47:28.633444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '291a9f0008ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='UQ_Permiso_Nombre'),
    schema='auth'
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='UQ_Rol_Nombre'),
    schema='auth'
    )
    op.create_table('especie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='UQ_Especie_Nombre'),
    schema='clinica'
    )
    op.create_table('domicilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('cp', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('calle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('altura', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('departamento', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('config_nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('parametro_id', sa.Integer(), nullable=False),
    sa.Column('parametro_nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('parametro_valor', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'parametro_id', name='UQ_Config_IDID'),
    schema='sys'
    )
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['auth.permiso.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['auth.rol.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id'),
    schema='auth'
    )
    op.create_table('raza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especie_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['especie_id'], ['clinica.especie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='clinica'
    )
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('domicilio_id', sa.Integer(), nullable=True),
    sa.Column('mail', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('celular', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domicilio_id'], ['core.domicilio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni', name='UQ_Persona_DNI'),
    schema='core'
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('version_token', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['core.persona.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['auth.rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', name='UQ_Usuario_Persona'),
    sa.UniqueConstraint('username', name='UQ_Usuario_Username'),
    schema='auth'
    )
    op.create_table('mascota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('raza_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('ultimo_peso', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['core.persona.id'], ),
    sa.ForeignKeyConstraint(['raza_id'], ['clinica.raza.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='clinica'
    )
    op.create_table('historial_contrasena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('debe_cambiar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['auth.usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('username_ingresado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('exito', sa.Boolean(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('razon_fallo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['auth.usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('historial_peso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('peso_kg', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['clinica.mascota.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mascota_id', 'fecha', name='UQ_HP_MascotaFecha'),
    schema='clinica'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_peso', schema='clinica')
    op.drop_table('login', schema='auth')
    op.drop_table('historial_contrasena', schema='auth')
    op.drop_table('mascota', schema='clinica')
    op.drop_table('usuario', schema='auth')
    op.drop_table('persona', schema='core')
    op.drop_table('raza', schema='clinica')
    op.drop_table('rol_permiso', schema='auth')
    op.drop_table('config', schema='sys')
    op.drop_table('domicilio', schema='core')
    op.drop_table('especie', schema='clinica')
    op.drop_table('rol', schema='auth')
    op.drop_table('permiso', schema='auth')
    # ### end Alembic commands ###
