name: CI y Merge a Main

on:
  push:
    branches: [ staging ]

jobs:
  pruebas-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulacion de CI
        run: echo "Aqui se ejecutaran tus CIs cuando los configures"

  fusionar-a-main:
    needs: pruebas-ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Actualizar main desde staging
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge origin/staging --ff-only
          git push origin main